from pathlib import Path

from src.utils.urls import (
    get_file_name,
    DATASET_TID2008_URL,
    DATASET_TID2013_URL,
    DATASET_KADID10K_URL
)

PROJECT_ROOT_PATH = Path(__file__).resolve().parent.parent.parent

CONFIGS_PATH = PROJECT_ROOT_PATH / 'configs/'

CONFIG_DATASET_KADID10K_PATH = CONFIGS_PATH / 'dataset_kadid10k.yaml'
CONFIG_DATASET_TID2008_PATH = CONFIGS_PATH / 'dataset_tid2008.yaml'
CONFIG_DATASET_TID2013_PATH = CONFIGS_PATH / 'dataset_tid2013.yaml'
CONFIG_DATASET_LIVE_PATH = CONFIGS_PATH / 'dataset_live.yaml'

CONFIG_MODEL_VIT_BASE_PATCH16_224_PATH = CONFIGS_PATH / 'model_vit_base_patch16_224.yaml'

CONFIG_TRAINING_KADID10K_VIT_BASE_PATCH16_224_BASELINE_PATH = CONFIGS_PATH / 'training_kadid10k_vit_base_patch16_224_baseline.yaml'
CONFIG_TRAINING_TID2008_VIT_BASE_PATCH16_224_BASELINE_PATH = CONFIGS_PATH / 'training_tid2008_vit_base_patch16_224_baseline.yaml'
CONFIG_TRAINING_TID2013_VIT_BASE_PATCH16_224_BASELINE_PATH = CONFIGS_PATH / 'training_tid2013_vit_base_patch16_224_baseline.yaml'
CONFIG_TRAINING_LIVE_VIT_BASE_PATCH16_224_BASELINE_PATH = CONFIGS_PATH / 'training_live_vit_base_patch16_224_baseline.yaml'

EXPERIMENTS_PATH = PROJECT_ROOT_PATH / 'experiments/'
EXPERIMENTS_KADID10K_PATH = EXPERIMENTS_PATH / 'kadid10k/'
EXPERIMENTS_TID2008_PATH = EXPERIMENTS_PATH / 'tid2008/'
EXPERIMENTS_TID2013_PATH = EXPERIMENTS_PATH / 'tid2013/'
EXPERIMENTS_LIVE_PATH = EXPERIMENTS_PATH / 'live/'

DATASETS_PATH = PROJECT_ROOT_PATH / 'datasets/'

DATASET_KADID10K_ARCHIVE_FILE_NAME = get_file_name(url=DATASET_KADID10K_URL)
DATASET_TID2008_ARCHIVE_FILE_NAME = get_file_name(url=DATASET_TID2008_URL)
DATASET_TID2013_ARCHIVE_FILE_NAME = get_file_name(url=DATASET_TID2013_URL)

DATASET_KADID10K_ARCHIVE_PATH = DATASETS_PATH / DATASET_KADID10K_ARCHIVE_FILE_NAME
DATASET_TID2008_ARCHIVE_PATH = DATASETS_PATH / DATASET_TID2008_ARCHIVE_FILE_NAME
DATASET_TID2013_ARCHIVE_PATH = DATASETS_PATH / DATASET_TID2013_ARCHIVE_FILE_NAME

SRC_PATH = PROJECT_ROOT_PATH / 'src/'
