from pathlib import Path

from src.utils.urls import (
    get_file_name,
    DATASET_TID2008_URL,
    DATASET_TID2013_URL,
    DATASET_KADID10K_URL
)

PROJECT_ROOT_PATH = Path(__file__).resolve().parent.parent.parent

CONFIGS_PATH = PROJECT_ROOT_PATH / 'configs/'
CONFIG_TRAIN_KADID10K_BASELINE_PATH = CONFIGS_PATH / 'train_kadid10k_vit_base_patch16_224_baseline.yaml'
CONFIG_TRAIN_TID2008_BASELINE_PATH = CONFIGS_PATH / 'train_tid2008_vit_base_patch16_224_baseline.yaml'
CONFIG_TRAIN_TID2013_BASELINE_PATH = CONFIGS_PATH / 'train_tid2013_vit_base_patch16_224_baseline.yaml'
CONFIG_TRAIN_LIVE_BASELINE_PATH = CONFIGS_PATH / 'train_live_vit_base_patch16_224_baseline.yaml'

EXPERIMENTS_PATH = PROJECT_ROOT_PATH / 'experiments/'
EXPERIMENTS_KADID10K_PATH = EXPERIMENTS_PATH / 'kadid10k/'
EXPERIMENTS_TID2008_PATH = EXPERIMENTS_PATH / 'tid2008/'
EXPERIMENTS_TID2013_PATH = EXPERIMENTS_PATH / 'tid2013/'
EXPERIMENTS_LIVE_PATH = EXPERIMENTS_PATH / 'live/'

DATASETS_PATH = PROJECT_ROOT_PATH / 'datasets/'

DATASET_TID2008_ARCHIVE_FILE_NAME = get_file_name(url=DATASET_TID2008_URL)
DATASET_TID2013_ARCHIVE_FILE_NAME = get_file_name(url=DATASET_TID2013_URL)
DATASET_KADID10K_ARCHIVE_FILE_NAME = get_file_name(url=DATASET_KADID10K_URL)

DATASET_TID2008_ARCHIVE_PATH = DATASETS_PATH / DATASET_TID2008_ARCHIVE_FILE_NAME
DATASET_TID2013_ARCHIVE_PATH = DATASETS_PATH / DATASET_TID2013_ARCHIVE_FILE_NAME
DATASET_KADID10K_ARCHIVE_PATH = DATASETS_PATH / DATASET_KADID10K_ARCHIVE_FILE_NAME

SRC_PATH = PROJECT_ROOT_PATH / 'src/'

